
#Problem definition:
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#						1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

f1 = 0
f2 = 1
term = 0
sum = 0
while term < 4000000:
    term = f1 + f2
    f1 = f2
    f2 =term
    if term%2 == 0:
        sum += term
print sum
